### ISSUE TITLE
List of Pages to Migrate

### ISSUE THREAD

**Issue by bstopp** [hlxsites/famous-smoke-cigaradvisor#1]
- [x] [https://www.famous-smoke.com/cigaradvisor](https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor) 
- [x] [https://www.famous-smoke.com/cigaradvisor/must-reads](https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/must-reads) ([PSI Score: 100/100](https://pagespeed.web.dev/analysis/https-main--famous-smoke-cigaradvisor--hlxsites-hlx-live-cigaradvisor-must-reads/qzbw29mw8d?form_factor=desktop))
- [x] [https://www.famous-smoke.com/cigaradvisor/videos](https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/videos) ([PSI Score: 94/100](https://pagespeed.web.dev/analysis/https-main--famous-smoke-cigaradvisor--hlxsites-hlx-live-cigaradvisor-videos/g6jqqj5h2h?form_factor=mobile))
  - #203
- [x] [https://www.famous-smoke.com/cigaradvisor/cigar-contest](https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/cigar-contest) ([PSI Score: 100/100](https://pagespeed.web.dev/analysis/https-main--famous-smoke-cigaradvisor--hlxsites-hlx-live-cigaradvisor-cigar-contest/kjqplf1b4n?form_factor=mobile))
- [x] [https://www.famous-smoke.com/cigaradvisor/cigar-guides](https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/cigar-guides) ([PSI Score: 100/100](https://pagespeed.web.dev/analysis/https-main--famous-smoke-cigaradvisor--hlxsites-hlx-live-cigaradvisor-cigar-guides/so3fzt5nvd?form_factor=mobile))
- [x] [https://www.famous-smoke.com/cigaradvisor/moreposts](https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/moreposts) ([PSI Score: 92/100](https://pagespeed.web.dev/analysis/https-main--famous-smoke-cigaradvisor--hlxsites-hlx-live-cigaradvisor-moreposts/pt44b7nbht?form_factor=mobile))
   - #207
- [x] [https://www.famous-smoke.com/cigaradvisor/author](https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/author) ([PSI Score: 100/100](https://pagespeed.web.dev/analysis/https-main--famous-smoke-cigaradvisor--hlxsites-hlx-live-cigaradvisor-author/0kkxumv5t4?form_factor=mobile))
- [x] [https://www.famous-smoke.com/cigaradvisor/about-us](https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/about-us) ([PSI Score: 94/100](https://pagespeed.web.dev/analysis/https-main--famous-smoke-cigaradvisor--hlxsites-hlx-live-cigaradvisor-about-us/l75uc53v09?form_factor=mobile))
  - #205
- [x] [https://www.famous-smoke.com/cigaradvisor/official-contest-rules](https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/official-contest-rules) ([PSI Score: 100/99](https://pagespeed.web.dev/analysis/https-main--famous-smoke-cigaradvisor--hlxsites-hlx-page-cigaradvisor-official-contest-rules/squvafnv7o?form_factor=mobile))
- [x] Category pages x 10 (Sample [PSI Score: 100/100](https://pagespeed.web.dev/analysis/https-main--famous-smoke-cigaradvisor--hlxsites-hlx-live-cigaradvisor-category-buying-guides/ozcl6b18fa?form_factor=mobile))
- [x] Author/Contributor pages x 86 (Sample [PSI Score: 98/100](https://pagespeed.web.dev/analysis/https-main--famous-smoke-cigaradvisor--hlxsites-hlx-live-cigaradvisor-author-cigar-advisor-staff/whak5y6f8g?form_factor=mobile))
  - #208
- [x] Post pages x 2560 (Sample [PSI Score: 86/82](https://pagespeed.web.dev/analysis/https-main--famous-smoke-cigaradvisor--hlxsites-hlx-live-cigaradvisor-category-buying-guides-cigar-advisor-guide-cle-cigars/nyeg59l8m1?form_factor=mobile))
  - #209

**Comment by kailasnadh790** [comment]
Notes:

- [ ] https://www.famous-smoke.com/cigaradvisor/author:  Need to update the list of curated authors once all the authors are indexed.

**Comment by tmaret** [comment]
Please reopen if we missed a page.
