### ISSUE TITLE
Contatct Us Form

### ISSUE THREAD

**Issue by bstopp** [hlxsites/famous-smoke-cigaradvisor#13]

**Comment by kailasnadh790** [comment]
Closing this issue based on confirmation from client: 
https://adobe-dx-support.slack.com/archives/C060KEF7DH9/p1703004496922969
<img width="822" alt="image" src="https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/53608019/281564e6-e8af-4def-90dc-3806abef910f">
