### ISSUE TITLE
Issues Post QA

### ISSUE THREAD

**Issue by kailasnadh790** [hlxsites/famous-smoke-cigaradvisor#131]
- [x]  ![image](https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/53608019/9e87480f-b5f4-4252-b03a-fb8283ec6c27)

URL: https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor

// EDIT @Kronnox: FIXED

**Comment by kailasnadh790** [comment]
- [ ] 
![Screenshot 2024-01-23 at 5 55 04 PM](https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/53608019/5dc2821a-ccaf-484e-b738-d36ab22fb396)

**Comment by kailasnadh790** [comment]
- [ ] 
![image](https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/53608019/f773f6ce-335c-4885-833e-bc02e7589248)
Contest form height and link below

**Comment by kailasnadh790** [comment]
![image](https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/53608019/b2841d23-18c8-45c6-9ea5-fa269a0db7d0)

Live site: 
![image](https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/53608019/c83127a0-c484-46d4-8c42-a39bc4165ce9)

**Comment by kailasnadh790** [comment]
Footer links : Need authoring and external links to be opened in new tab

**Comment by kailasnadh790** [comment]
- [ ] https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/cigar-guides :  right column images stretched to occupy the height

**Comment by kailasnadh790** [comment]
- [ ] https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/about-us : Image taking full width compared to live site.

**Comment by kailasnadh790** [comment]
- [ ] ![image](https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/53608019/77fb6444-0458-46d5-8983-6bb3717a9172)
Fix the height of the author

**Comment by kailasnadh790** [comment]
- [ ] ![image](https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/53608019/45ea1746-4181-4083-9c6e-6e89c520eead)

**Comment by bstopp** [comment]
Can we close this issue?

**Comment by kailasnadh790** [comment]
@bstopp only pending/untracked issue here is https://github.com/hlxsites/famous-smoke-cigaradvisor/issues/131#issuecomment-1912311711 .

**Comment by kailasnadh790** [comment]
- [ ] <img width="841" alt="image" src="https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/53608019/a4f28684-3490-472d-af8a-cac181123804">
social icons are shifted up.

**Comment by bstopp** [comment]
Closing this issue - any new ones should be individual backlog bugs.
