### ISSUE TITLE
Search Form & Search Results

### ISSUE THREAD

**Issue by bstopp** [hlxsites/famous-smoke-cigaradvisor#14]
Looks like it only searches the articles.

Probably should still have a dedicated search results page w/ the block on it.

<img width="590" alt="search" src="https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/6520270/e1ee8bb5-eca1-4129-af87-ec4781ed2104">

**Comment by kailasnadh790** [comment]
![image](https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/53608019/fa18e9ab-a0d1-48c9-8c5b-32fad0ac5aa0)
