### ISSUE TITLE
Height difference between CTA Image and Article Teasers

### ISSUE THREAD

**Issue by Kronnox** [hlxsites/famous-smoke-cigaradvisor#179]
Between the two breakpoints `900px` and `1200px` there will be a difference in the height of the left and right side:

![Screenshot 2024-01-31 at 13 31 31](https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/28481491/111692fe-e5c5-44ff-b515-11aa5f3b1512)

Scaling of the articles and the CTA Image seems to differ from the original site (no idea what is the "correct behaviour" here).

As a side note. The color of the `Read More >` also changes on the original site. On the AEM version it's black all the time.

**Comment by kailasnadh790** [comment]
@Kronnox Looks like the height issue is gone if we refresh the page after switching to those viewports. So, I guess it should be fine on devices.

**Comment by kailasnadh790** [comment]
![image](https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/53608019/c1a02ad4-6806-4db2-917e-2c7a2c311f76)
