### ISSUE TITLE
Artcile Page Structure

### ISSUE THREAD

**Issue by bstopp** [hlxsites/famous-smoke-cigaradvisor#18]
Metadata:
* Category
* Author 
* Read Time
* Published Date
* Promo-blurb (for search and teasers)

**Comment by tmaret** [comment]
Sample article and author documents 

* https://famoussmokeshop.sharepoint.com/:w:/r/sites/AEM/webroot/www/cigaradvisor/cigaradvisor/drafts/tmaret/how-long-it-takes-to-make-a-cigar.docx
* https://famoussmokeshop.sharepoint.com/:w:/r/sites/AEM/webroot/www/cigaradvisor/cigaradvisor/author/drafts/john-pullo.docx
