### ISSUE TITLE
Header styling

### ISSUE THREAD

**Issue by Kronnox** [hlxsites/famous-smoke-cigaradvisor#180]
A few discrepancies between the header on the original site and the AEM version:

- [ ] The navigation links are too high up and are obstructed by the logo:
![Screenshot 2024-01-31 at 13 38 06](https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/28481491/930c0c81-1858-4e42-8669-1972327884cf)

- [ ] The text content of the partner site links should be trimmed down on a lower resolution breakpoint and the word wrap is a bit messed up:
![Screenshot 2024-01-31 at 13 38 34](https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/28481491/6c4353af-125a-4f8b-a152-d7aa549c95af)

- [ ] The social media icons are at a different height (might not be an issue):
![Screenshot 2024-01-31 at 13 38 44](https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/28481491/32bc424e-9014-4d4f-bad6-0c7f14cedcb8)

**Comment by bstopp** [comment]
Not sure I agree with the second one. The word wrap was introduced due to this experience on the live site:

<img width="530" alt="compariison" src="https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/6520270/8edb719d-2614-4f06-a72e-c9790ad3c25d">

**Comment by bstopp** [comment]
> The social media icons are at a different height (might not be an issue):

yeah, that was intentional too, as you can see from the previous comment, they are also more vertically aligned to center in the new site.
