### ISSUE TITLE
Import posts with paths bucketed by category

### ISSUE THREAD

**Issue by tmaret** [hlxsites/famous-smoke-cigaradvisor#182]
- [x] remove the `readingTime` from the post metadata
- [x] update links in the post content and metadata to point to the bucketed path (no redirect)
- [x] (optional) rewrite links based on a redirect provided by the customer
- [x] fix image alt text import such that it can be edited in the image itself (currently provided as a `em` tag)
- [x] build the redirect.xlsx (to support existing links in the wild that point to the current paths under the site root)

**Comment by tmaret** [comment]
Paths listed from home page https://github.com/hlxsites/famous-smoke-cigaradvisor/issues/114

**Comment by bstopp** [comment]
can run `npm run generate-redirects` to use the side metadata to create the list as a CSV. I didn't know if we wanted to commit that file to the branch.

**Comment by tmaret** [comment]
Ah, and the file is invoked directly by the importer tool, correct ?

**Comment by bstopp** [comment]
> Ah, and the file is invoked directly by the importer tool, correct ?

No, in this case it needs to be run before the importer to generate the sidecar data. Both the metadata and redirects need to be run manually.

**Comment by tmaret** [comment]
customer redirects done via https://github.com/hlxsites/famous-smoke-cigaradvisor/issues/223
