### ISSUE TITLE
Author Reference Block

### ISSUE THREAD

**Issue by bstopp** [hlxsites/famous-smoke-cigaradvisor#19]
Used on Author landing and Article page

Pull the data from remote page, so as to not repeat info

<img width="551" alt="author" src="https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/6520270/051b6a9d-e6a8-42e0-927f-c4cd2a5478c7">

**Comment by tmaret** [comment]
https://github.com/hlxsites/famous-smoke-cigaradvisor/tree/author-block
