### ISSUE TITLE
Vimeo Player can cause issues with PSI Score

### ISSUE THREAD

**Issue by bstopp** [hlxsites/famous-smoke-cigaradvisor#196]
[This page](https://feat-image-urls--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/category/cigar-reviews/my-weekend-cigar-review-red-meat-lovers-filet-mignon) has it within the initial viewport, which causes it to load immediately.

We may not be able to get away with just an intersection observer for loading this or other libraries/players.

**Comment by Kronnox** [comment]
That's actually a tricky one. I know of a few ways this could be improved for above the fold videos, but all of the solutions are either quite complex or require external libraries. Not sure if it's worth it.

**Comment by bstopp** [comment]
There's always the option of requiring the placeholder and swapping it out on click - but that assumes they provide one.

**Comment by bstopp** [comment]
Closing this - if the issue appears in the RUM reporting, we'll look to address it then.
