### ISSUE TITLE
Header Block

### ISSUE THREAD

**Issue by bstopp** [hlxsites/famous-smoke-cigaradvisor#2]
<img width="638" alt="header" src="https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/6520270/fa115820-ae2a-4af8-821d-3d23d0c23b46">

**Comment by tmaret** [comment]
The header is consistent for all CA pages and does not seem to be reused over other sections of the site. As we are migrating all CA, I think we can hard code the header in a document (no need to fetch it). 

@bstopp wdyt ?
