### ISSUE TITLE
Fix Icon alignment

### ISSUE THREAD

**Issue by bstopp** [hlxsites/famous-smoke-cigaradvisor#219]
<img width="561" alt="Cigar_Advisor_-__1_Cigar_Magazine_for_Cigar_Reviews" src="https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/6520270/3e152743-e9b9-49f7-af27-3194cccc305d">

**Comment by kailasnadh790** [comment]
@bstopp I guess, we still haven't got correct svg images. these are just placeholders .
