### ISSUE TITLE
Remove Article Recommendations from Import

### ISSUE THREAD

**Issue by bstopp** [hlxsites/famous-smoke-cigaradvisor#224]
Remove the logic that adds recommended articles from the import process.

**Comment by tmaret** [comment]
Recommendation will be injected dynamically thanks to https://github.com/hlxsites/famous-smoke-cigaradvisor/pull/226

**Comment by tmaret** [comment]
https://github.com/hlxsites/famous-smoke-cigaradvisor/commit/68884498c7e06d6a16d5879b921532e0ef858fbd
