### ISSUE TITLE
Content: Remove `category` from all URL paths.

### ISSUE THREAD

**Issue by Kronnox** [hlxsites/famous-smoke-cigaradvisor#228]
Related to #221.

**Comment by tmaret** [comment]
Updated the importer piece that generate posts links

https://github.com/hlxsites/famous-smoke-cigaradvisor/commit/8f7147499dae25178bf7c84381492d457afa0b8a

**Comment by tmaret** [comment]
Updated the footer https://famoussmokeshop.sharepoint.com/:w:/r/sites/AEM/webroot/www/cigaradvisor/cigaradvisor/[footer.docx](https://famoussmokeshop.sharepoint.com/:w:/r/sites/AEM/webroot/www/cigaradvisor/cigaradvisor/footer.docx?d=w0ae6983b24304066ae269fc53fd84ddb&csf=1&web=1&e=VqjkQE)?d=w0ae6983b24304066ae269fc53fd84ddb&csf=1&web=1&e=VqjkQE

**Comment by tmaret** [comment]
Updated https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/must-reads

**Comment by tmaret** [comment]
Updated https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/nav

**Comment by tmaret** [comment]
Moved the existing categories one level up
