### ISSUE TITLE
Indexes Needed

### ISSUE THREAD

**Issue by bstopp** [hlxsites/famous-smoke-cigaradvisor#23]
* [x] Site index
* [x] Author Index
  * ID (or URL)
  * Full name
  * Description
  * Profile picture
  * Twitter
  * Facebook
  * Instagram
  * Youtube
* [x] Article Index
  * Title
  * Author name
  * Publishing date
  * Reading time
  * Teaser text
  * Teaser image
  * URL
  * Category

**Comment by tmaret** [comment]
@Kronnox properties LGTM. How about updating the list with the metadata key we'd use ? That'd serve as an interface between indexing and importing.
