### ISSUE TITLE
Hero isn't the LCP on the frontpage

### ISSUE THREAD

**Issue by Kronnox** [hlxsites/famous-smoke-cigaradvisor#234]
The hero section should be the LCP on the home page, however, the promotion banner is chosen as the LCP instead.

<img width="964" alt="Screenshot 2024-02-27 at 11 47 24" src="https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/28481491/534eb605-570f-414c-9585-af34fc88efea">

**Comment by bstopp** [comment]
this is only on the Desktop view, correct?

**Comment by Kronnox** [comment]
> this is only on the Desktop view, correct?

I also saw it happening on mobile
