### ISSUE TITLE
Sort article list by published date from newest to oldest

### ISSUE THREAD

**Issue by tmaret** [hlxsites/famous-smoke-cigaradvisor#244]
The articles listed in category pages such as https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/buying-guides#page=5 and https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/moreposts page are currently un-ordered. We'd need to order them by publication date.

**Comment by bstopp** [comment]
This has been fixed
