### ISSUE TITLE
Add robots.txt

### ISSUE THREAD

**Issue by Kronnox** [hlxsites/famous-smoke-cigaradvisor#247]
- [ ] Include a robots.txt in the code root
- [ ] Clarify how it will work, since this is technically only a subsite
- [ ] Reference sitemaps / sitemap index

**Comment by bstopp** [comment]
You can't use a Robots.txt in any location other than the root - in this case `www.famous-smoke.com/`; so we must rely on the top site to reference our Sitemap.
