### ISSUE TITLE
Article Page "You may also like..." doesn't always display 4

### ISSUE THREAD

**Issue by bstopp** [hlxsites/famous-smoke-cigaradvisor#250]

**Comment by tmaret** [comment]
Example https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/buying-guides/new-cigars-march-4-2024 

shows 3 entries

**Comment by tmaret** [comment]
https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/buying-guides/top-rated-connecticut-wrapper-cigars-under-10

**Comment by tmaret** [comment]
All articles in the https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/buying-guides

**Comment by tmaret** [comment]
There are a few issues

- [] the random selection logic for must read articles does not accept the article at index `0` which can occurs around once every 30 pages
- [] Some authors have a single article
- [] `fetchPostsInfo` returns an empty array for some articles like `/cigaradvisor/buying-guides/cigars-for-beginners`, `/cigaradvisor/cuban-cigar-guides/how-to-spot-fake-cuban-cigars`, or `/cigaradvisor/buying-guides/2017-best-cigar-cutters-readers-choice`
