### ISSUE TITLE
High TBT on must-read page

### ISSUE THREAD

**Issue by tmaret** [hlxsites/famous-smoke-cigaradvisor#260]
As measured on https://github.com/hlxsites/famous-smoke-cigaradvisor/issues/243

[https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/must-reads](https://pagespeed.web.dev/analysis/https-main--famous-smoke-cigaradvisor--hlxsites-hlx-live-cigaradvisor-must-reads/abgr4ovcek?form_factor=mobile) (PSI 84/100)

**Comment by Kronnox** [comment]
It's really weird. The hight TBT only seems to be present on PSI. I can't really reproduce it locally or determine where it's coming from

**Comment by tmaret** [comment]
![Screenshot 2024-03-11 at 14 16 43](https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/1628648/ee659413-e7e7-4750-9575-b28ccc2ac5f3)

renderByList seems to be taking 90ms and be flagged as a long task

**Comment by tmaret** [comment]
Potentially linked to https://github.com/hlxsites/famous-smoke-cigaradvisor/blob/main/cigaradvisor/blocks/article-list/article-list.js#L100-L103 which does 30x2500 iterations

**Comment by Kronnox** [comment]
Could possibly be improved. But still, 90ms is near to nothing in comparison to the 3000ms PSI is measuring. But I'm not able to reproduce that on my own machine, to get further details
