### ISSUE TITLE
High LCP on moreposts and author pages

### ISSUE THREAD

**Issue by tmaret** [hlxsites/famous-smoke-cigaradvisor#261]
As measured in https://github.com/hlxsites/famous-smoke-cigaradvisor/issues/243

* [https://main--famous-smoke-cigaradvisor--hlxsites.hlx.live/cigaradvisor/moreposts](https://pagespeed.web.dev/analysis/https-main--famous-smoke-cigaradvisor--hlxsites-hlx-live-cigaradvisor-moreposts/3p3k5hf8sc?form_factor=mobile) (PSI 86/100)

**Comment by kailasnadh790** [comment]
![Screenshot 2024-03-07 at 12 32 31 PM](https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/53608019/d9db4d91-036b-4ba2-af7c-fe00eed9053f)

https://main--famous-smoke-cigaradvisor--hlxsites.hlx.live/cigaradvisor/author/cigar-advisor-staff consistently giving good scores now.

**Comment by tmaret** [comment]
Thank you @kailasnadh790 ! I get the same numbers now. Updating the tickets.
