### ISSUE TITLE
Grid Layout Section

### ISSUE THREAD

**Issue by bstopp** [hlxsites/famous-smoke-cigaradvisor#5]
Tall Left: 

<img width="565" alt="Grid_Layout_Left" src="https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/6520270/aa9a9888-a8da-4a76-9ed5-c4965b5cf5af">

Tall Right:

<img width="556" alt="Tall_Right" src="https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/6520270/3018c543-ced9-47bd-a8b3-55d9f0477bbf">

**Comment by kailasnadh790** [comment]
@bstopp 
![image](https://github.com/hlxsites/famous-smoke-cigaradvisor/assets/53608019/4406b498-b293-4b00-a050-5c9cd17d4c44)

**Comment by tmaret** [comment]
Looking at the [cigars-101](https://www.famous-smoke.com/cigaradvisor/category/cigars-101) post, it seems that the description is authored.

**Comment by bstopp** [comment]
The "blurb" isn't found anywhere on the actual article page. So it'll come from the Metadata. This ticket though is just regarding the layout of the blocks - tickets #6  and #7  are for the individual items in the layout.
